In [34]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [35]:
iris =load_iris()

In [37]:
#Logistic Regression

l_scores = cross_val_score(LogisticRegression(max_iter=1000), iris.data, iris.target, cv=3)
l_scores

array([0.98, 0.96, 0.98])

In [38]:
np.average(l_scores)

0.9733333333333333

In [39]:
#Decision Tree

D_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target, cv=3)
D_scores

array([0.98, 0.94, 0.98])

In [40]:
np.average(D_scores)

0.9666666666666667

In [41]:
#Support Vector Machine (SVM)

s_scores = cross_val_score(SVC(), iris.data, iris.target, cv=3)
s_scores

array([0.96, 0.98, 0.94])

In [42]:
np.average(s_scores)

0.96

In [43]:
#Random Forest

R_scores = cross_val_score(RandomForestClassifier(), iris.data, iris.target, cv=3)
R_scores

array([0.98, 0.94, 0.96])

In [44]:
np.average(R_scores)

0.96